before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - name: getgitignore
    license: "MIT"
    description: "Tool to get Git Ignore files from GitHub GitIgnore"
    homepage: "https://github.com/joeds13/getgitignore"
    tap:
      owner: joeds13
      name: homebrew-tap
    folder: Formula
    test: |
      system "#{bin}/getgitignore version"
    install: |
      bin.install "getgitignore"
